- description: null
  label: "FAQ"
  name: "faq"
  sort: 1
  listed: true
  hasRoute: true
  showAsTable: false
  parent: null
  fields:
    - name: "url"
      label: "URL"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "header_text"
      label: "Heading"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "sub_header"
      label: "Sub Heading"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "sub_text"
      label: "List Summary"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
    - name: "featured_image"
      label: "Featured Image"
      description: null
      datatype: "images"
      sort: 1
      required: null
      relationship: null
      settings:
        limit: 1
        list: false
    - name: "featured_image_alt"
      label: "Featured Image Alt Text"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "featured_video"
      label: "Featured Video"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "schemamarkup"
      label: "Schema Markup"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "body"
      label: "Body"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
- description: null
  label: "Application Questions"
  name: "application_questions"
  sort: 1
  listed: true
  hasRoute: true
  showAsTable: true
  parent: "faq"
  fields:
    - name: "url"
      label: "URL"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "header_text"
      label: "Heading"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "sub_header"
      label: "Sub Heading"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "sub_text"
      label: "List Summary"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
    - name: "featured_image"
      label: "Featured Image"
      description: null
      datatype: "images"
      sort: 1
      required: null
      relationship: null
      settings:
        limit: 1
        list: false
    - name: "featured_image_alt"
      label: "Featured Image Alt Text"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "featured_video"
      label: "Featured Video"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "schemamarkup"
      label: "Schema Markup"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "body"
      label: "Body"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
- description: null
  label: "Claims Questions"
  name: "claims_questions"
  sort: 1
  listed: true
  hasRoute: true
  showAsTable: true
  parent: "faq"
  fields:
    - name: "url"
      label: "URL"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "header_text"
      label: "Heading"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "sub_header"
      label: "Sub Heading"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "sub_text"
      label: "List Summary"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
    - name: "featured_image"
      label: "Featured Image"
      description: null
      datatype: "images"
      sort: 1
      required: null
      relationship: null
      settings:
        limit: 1
        list: false
    - name: "featured_image_alt"
      label: "Featured Image Alt Text"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "featured_video"
      label: "Featured Video"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "schemamarkup"
      label: "Schema Markup"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "body"
      label: "Body"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
- description: null
  label: "Cost Questions"
  name: "cost_questions"
  sort: 1
  listed: true
  hasRoute: true
  showAsTable: true
  parent: "faq"
  fields:
    - name: "url"
      label: "URL"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "header_text"
      label: "Heading"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "sub_header"
      label: "Sub Heading"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "sub_text"
      label: "List Summary"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
    - name: "featured_image"
      label: "Featured Image"
      description: null
      datatype: "images"
      sort: 1
      required: null
      relationship: null
      settings:
        limit: 1
        list: false
    - name: "featured_image_alt"
      label: "Featured Image Alt Text"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "featured_video"
      label: "Featured Video"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "schemamarkup"
      label: "Schema Markup"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "body"
      label: "Body"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
- description: null
  label: "Home Insurance Coverage Questions"
  name: "home_insurance-coverage-questions"
  sort: 1
  listed: true
  hasRoute: true
  showAsTable: true
  parent: "faq"
  fields:
    - name: "url"
      label: "URL"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "header_text"
      label: "Heading"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "sub_header"
      label: "Sub Heading"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "sub_text"
      label: "List Summary"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
    - name: "featured_image"
      label: "Featured Image"
      description: null
      datatype: "images"
      sort: 1
      required: null
      relationship: null
      settings:
        limit: 1
        list: false
    - name: "featured_image_alt"
      label: "Featured Image Alt Text"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "featured_video"
      label: "Featured Video"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "schemamarkup"
      label: "Schema Markup"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "body"
      label: "Body"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
- description: null
  label: "Homeownership Questions"
  name: "homeownership_questions"
  sort: 1
  listed: true
  hasRoute: true
  showAsTable: true
  parent: "faq"
  fields:
    - name: "url"
      label: "URL"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "header_text"
      label: "Heading"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "sub_header"
      label: "Sub Heading"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "sub_text"
      label: "List Summary"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
    - name: "featured_image"
      label: "Featured Image"
      description: null
      datatype: "images"
      sort: 1
      required: null
      relationship: null
      settings:
        limit: 1
        list: false
    - name: "featured_image_alt"
      label: "Featured Image Alt Text"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "featured_video"
      label: "Featured Video"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "schemamarkup"
      label: "Schema Markup"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "body"
      label: "Body"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
- description: null
  label: "Policy Questions"
  name: "policy_questions"
  sort: 1
  listed: true
  hasRoute: true
  showAsTable: true
  parent: "faq"
  fields:
    - name: "url"
      label: "URL"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "header_text"
      label: "Heading"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "sub_header"
      label: "Sub Heading"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "sub_text"
      label: "List Summary"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
    - name: "featured_image"
      label: "Featured Image"
      description: null
      datatype: "images"
      sort: 1
      required: null
      relationship: null
      settings:
        limit: 1
        list: false
    - name: "featured_image_alt"
      label: "Featured Image Alt Text"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "featured_video"
      label: "Featured Video"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "schemamarkup"
      label: "Schema Markup"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "body"
      label: "Body"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
